Repository kowainik/kowainik.github.io, pull requests merged in 2018-06, with the labels that each got.

#10 [#5] Add post template, all posts page and tags page
  README.md
  css/default.css
  css/main.css
  css/post.css
  favicon.ico
  fonts/Noteworthy-Lt.woff
  images/logo-tr.png
  site.hs
  stack.yaml
  templates/404.html
  templates/main.html
  templates/post.html
  templates/posts-default.html
  templates/posts.html
  templates/tag.html
  website.cabal
Labels: enhancement, web-page

#11 Add first blog post about build tools
  css/post.css
  posts/2018-06-21-haskell-build-tools.md
  templates/posts.html
Labels: content

#12 Add some changes to build-tools blog post
  posts/2018-06-21-haskell-build-tools.md
Labels: content

#14 [#13] Get project pages unde projects/ link
  .gitignore
  css/default.css
  css/post.css
  js/stars.js
  site.hs
  src/Kowainik/Readme.hs
  templates/readme.html
  templates/readmes.html
  website.cabal
Labels: enhancement, project-page
