Repository kowainik/kowainik.github.io, pull requests merged in 2018-09, with the labels that each got.

#33 Add meta data
  templates/404.html
  templates/main.html
Labels: web-page

#34 [#25] Add Hakyll link at the main page
  templates/footer.html
Labels: landing, web-page

#36 [#35] Add Dhall to Hlint post
  css/post.css
  posts/2018-09-09-dhall-to-hlint.md
Labels: content

#38 Update asciicast link
  posts/2018-06-21-haskell-build-tools.md
Labels: content

#42 Add google analytics
  templates/main.html
  templates/posts-default.html
Labels: enhancement

#41 [#39] Add toc, make links on headers
  .gitignore
  README.md
  css/post.css
  posts-raw/2018-06-21-haskell-build-tools.md
  posts-raw/2018-07-11-typerep-map-step-by-step.md
  posts-raw/2018-08-19-picnic-put-containers-into-a-backpack.md
  posts-raw/2018-09-09-dhall-to-hlint.md
  site.hs
  src/Kowainik/Post.hs
  src/Kowainik/Readme.hs
  stack.yaml
  templates/post.html
  website.cabal
Labels: enhancement, web-page

#47 [#44] Build with cabal
  website.cabal
Labels: CI

#48 [#32] Add co-log blog post
  .gitignore
  css/post.css
  posts-raw/2018-09-25-co-log.md
Labels: content

#52 [#51] Make all links w/o html extension
  posts-raw/2018-09-25-co-log.md
  site.hs
  templates/404.html
  templates/post.html
  templates/posts.html
  templates/readme.html
  templates/readmes.html
  website.cabal
Labels: web-page

#53 [#46] Add link to the video
  posts-raw/2018-08-19-picnic-put-containers-into-a-backpack.md
Labels: content

#55 [#54] Add Hacktoberfest announcement
  posts-raw/2018-10-01-hacktoberfest.md
Labels: content
