Repository kowainik/kowainik.github.io, pull requests merged in 2018-08, with the labels that each got.

#18 [#6] Add join us and blog sections
  images/blog.svg
  images/joinus.svg
  templates/main.html
  templates/nav.html
Labels: landing, web-page

#21 [#7] Update projects
  css/main.css
  images/projects/cabin.png
  images/projects/circus.png
  images/projects/containers-backpack.png
  images/projects/game.png
  images/projects/idris-patricia.png
  images/projects/life-sync.png
  images/projects/relude.png
  images/projects/safe.png
  images/projects/smuggler.png
  images/projects/submarine.png
  images/projects/summoner.png
  images/projects/typerep-map.png
  site.hs
  src/Kowainik/Project.hs
  templates/main.html
  templates/nav.html
  templates/posts-default.html
  templates/project.html
Labels: landing, refactoring, web-page

#22 [#9] Pretify the team section
  images/team/dmitrii.kovanikov.png
  images/team/dmitry.kovanikov.jpg
  images/team/veronika.romashkina.jpeg
  images/team/veronika.romashkina.png
  images/team/vladislav.sabanov.png
  src/Kowainik/Team.hs
  templates/footer.html
  templates/main.html
  templates/team.html
Labels: landing, web-page

#23 [#15] Improve cabal part in blog post
  posts/2018-06-21-haskell-build-tools.md
Labels: content

#30 [#29] Read team members via json file
  site.hs
  src/Kowainik/Team.hs
  team.json
Labels: landing, refactoring, web-page
