Repository kowainik/kowainik.github.io, pull requests merged in 2019-07, with the labels that each got.

#84 Minor updates to blog posts
  posts/2018-09-25-co-log.md
  posts/2018-11-18-state-pattern-matching.md
  posts/2019-01-14-tomland.md
Labels: content

#86 [#85] Improve projects page
  src/Kowainik/Readme.hs
  templates/posts.html
  templates/readmes.html
Labels: enhancement, project-page

#90 [#88] Introduce hakyll-shortcut-links
  kowainik-site.cabal
  posts/2018-07-11-typerep-map-step-by-step.md
  site.hs
Labels: library

#91 Add membrain blog post
  css/default.css
  css/post.css
  posts/2018-07-11-typerep-map-step-by-step.md
  posts/2018-08-19-picnic-put-containers-into-a-backpack.md
  posts/2018-09-25-co-log.md
  posts/2019-01-14-tomland.md
  posts/2019-07-23-membrain.md
  templates/posts-default.html
Labels: content, enhancement
