Repository kowainik/kowainik.github.io, pull requests merged in 2019-01, with the labels that each got.

#65 Migrate to GHC 8.6.3 and update some blog posts
  posts-raw/2018-06-21-haskell-build-tools.md
  posts-raw/2018-07-11-typerep-map-step-by-step.md
  posts-raw/2018-08-19-picnic-put-containers-into-a-backpack.md
  posts-raw/2018-09-09-dhall-to-hlint.md
  stack.yaml
  website.cabal
Labels: CI, content

#66 Add tomland blog post
  posts-raw/2019-01-14-tomland.md
Labels: content

#67 Grammar fixes for tomland blog post
  posts-raw/2018-07-11-typerep-map-step-by-step.md
  posts-raw/2019-01-14-tomland.md
Labels: content

#70 Maake font in tags smaller so it can fit small screens
  css/default.css
  css/post.css
Labels: bug
