Repository kowainik/kowainik.github.io, pull requests merged in 2019-11, with the labels that each got.

#105 Use relude-0.6.0.0
  .travis.yml
  kowainik-site.cabal
Labels: library

#106 [#80] Move to FontAwesome 5
  css/default.css
  css/font-awesome.css
  fonts/FontAwesome.otf
  fonts/fontawesome-webfont.eot
  fonts/fontawesome-webfont.svg
  fonts/fontawesome-webfont.ttf
  fonts/fontawesome-webfont.woff
  fonts/fontawesome-webfont.woff2
  src/Kowainik/Social.hs
  templates/404.html
  templates/footer.html
  templates/main.html
  templates/posts-default.html
  templates/readmes.html
  templates/team.html
Labels: refactoring, web-page

#107 Change slogan
  templates/main.html
Labels: landing

#108 Update footer
  templates/footer.html
Labels: landing
