Repository kowainik/kowainik.github.io, pull requests merged in 2020-03, with the labels that each got.

#110 [#93] Move to GHC-8.8.1
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .travis.yml
  README.md
  app/Main.hs
  cabal.project
  kowainik-site.cabal
  src/Kowainik.hs
  src/Kowainik/Readme.hs
Labels: enhancement, library, refactoring

#111 More granular team separation
  core.json
  src/Kowainik.hs
  src/Kowainik/Team.hs
  team.json
  templates/main.html
Labels: enhancement, web-page

#112 Prelude usage update, minor refactoring
  kowainik-site.cabal
  src/Kowainik.hs
  src/Kowainik/Team.hs
  src/Prelude.hs
  team/creators.json
  team/volunteers.json
  templates/main.html
Labels: refactoring

#114 [#113] Fetch more pages of projects
  src/Kowainik/Readme.hs
Labels: project-page
