Repository kowainik/kowainik.github.io, pull requests merged in 2020-12, with the labels that each got.

#148 [#147] Haddock blog post
  css/post.css
  images/haddock/doc-thor.jpg
  images/haddock/fish.png
  images/haddock/haddock-ascii-border.png
  images/haddock/haddock-ascii-prolens.png
  images/haddock/haddock-expandable-example.gif
  images/haddock/haddock-extensions.png
  images/haddock/haddock-membrain.png
  images/haddock/haddock-missing-line-doc.png
  images/haddock/haddock-named-chunks.png
  images/haddock/haddock-no-docs.jpg
  images/haddock/haddock-our-toc-view.png
  images/haddock/haddock-overall-example.png
  images/haddock/haddock-prolens-toc.png
  images/haddock/haddock-reanimate-gif.gif
  images/haddock/haddock-relude-search.png
  images/haddock/haddock-relude-string.png
  images/haddock/haddock-tomland-import-only.png
  images/haddock/haddock-tomland-links.png
  images/haddock/haddock-top-level-header.png
  images/haddock/haddock-warnings.png
  images/haddock/haddock-xzibit.jpg
  posts/2019-02-06-style-guide.md
  posts/2020-12-07-haddock-tips.md
Labels: content

#150 [#149] Add dependabot
  .github/dependabot.yml
Labels: CI, library

#153 [#142] Email subscription
  css/default.css
  css/main.css
  css/post.css
  images/bell.png
  images/joinus.svg
  src/Kowainik.hs
  src/Kowainik/Nav.hs
  team/volunteers.json
  templates/main.html
  templates/post.html
  templates/subscribe.html
Labels: idea

#156 [#155] Naming conventions blog post
  css/post.css
  posts/2020-12-13-naming-conventions.md
Labels: blog

#157 Fix error in Naming conventions post (s/suffix/prefix)
  posts/2020-12-13-naming-conventions.md
Labels: typo
