Repository kowainik/kowainik.github.io, pull requests merged in 2020-06, with the labels that each got.

#123 [#122] Improve inline code blocks
  css/default.css
  css/post.css
Labels: web-page

#124 Adjust CI settings
  .github/workflows/ci.yml
Labels: CI

#126 [#125] Update highlighted projects
  images/projects/co-log.png
  images/projects/colourista.png
  images/projects/extensions.png
  images/projects/policeman.png
  images/projects/relude.png
  images/projects/stan.png
  images/projects/validation-selective.png
  src/Kowainik/Project.hs
Labels: content, project-page
